### ISSUE TITLE
wiki proofread

### ISSUE THREAD

**Issue by fjod** [reinforced/Reinforced.Tecture#2]
Some proofreading

https://github.com/fjod/Reinforced-wiki

because github does not have PR-functionality for wiki. Based on:
https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by pavel-b-novikov** [comment]
Merged через жопу.
Thanks, @fjod. I appreciate your work like never before.

**Comment by AxelUser** [comment]
@pavel-b-novikov why not just put those files into "docs" folder in repository? This became really handy, when looking for docs at specific version (tag).

**Comment by pavel-b-novikov** [comment]
I will do that as far as I finish with other media work regarding Tecture.

Also it is not good idea because every commit to it will trigger Github Action that builds Tecture
